// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {CoreFixture} from "./utils/CoreFixture.sol";
import {IRevenueRouter} from "../../src/interfaces/IRevenueRouter.sol";
import {MockERC20} from "../../src/mocks/MockERC20.sol";

/// @notice Parity with the NORMATIVE TypeScript `splitDistribution` (packages/shared/src/waterfall.ts).
///         Vectors: test/vectors/waterfall.json, generated by scripts/gen-vectors.ts. Each `split` row is
///         [gross, expensesRequested, expenseCapBps, carryBps, seniorHurdleBps, seniorSupply, juniorSupply,
///          expenses, carry, senior, junior].
contract RevenueRouterParityTest is CoreFixture {
    function _json() internal view returns (string memory) {
        return vm.readFile(string.concat(vm.projectRoot(), "/test/vectors/waterfall.json"));
    }

    /// @dev Parses row `i` of `.split`. The free-memory pointer is restored after the cheatcode call so the
    ///      ~125KB JSON argument copy is not leaked once per row (memory cost is quadratic).
    function _row(string memory json, uint256 i) internal pure returns (uint256[11] memory out) {
        string memory key = string.concat(".split[", vm.toString(i), "]");
        uint256 fmp;
        assembly ("memory-safe") {
            fmp := mload(0x40)
        }
        uint256[] memory r = vm.parseJsonUintArray(json, key);
        require(r.length == 11, "row width");
        for (uint256 k; k < 11; ++k) {
            out[k] = r[k];
        }
        assembly ("memory-safe") {
            mstore(0x40, fmp)
        }
    }

    function _count(string memory json) internal pure returns (uint256) {
        return vm.parseJsonUint(json, ".count");
    }

    function _check(IRevenueRouter.Amounts memory a, uint256[11] memory r, uint256 i) internal pure {
        if (a.gross != r[0] || a.expenses != r[7] || a.carry != r[8] || a.senior != r[9] || a.junior != r[10])
        {
            revert(string.concat("split parity mismatch at row ", vm.toString(i)));
        }
    }

    function test_vectorsPresent() public view {
        assertEq(_count(_json()), 256);
    }

    /// @dev Pure helper reproduces every row exactly.
    function test_parity_computeSplit() public view {
        string memory json = _json();
        uint256 n = _count(json);
        for (uint256 i; i < n; ++i) {
            uint256[11] memory r = _row(json, i);
            _check(router.computeSplit(r[0], r[1], r[2], r[3], r[4], r[5], r[6]), r, i);
        }
    }

    /// @dev previewSplit, reading live config params, the book's charter hurdle and tranche supplies,
    ///      reproduces every row exactly.
    function test_parity_previewSplit() public {
        string memory json = _json();
        uint256 n = _count(json);
        for (uint256 i; i < n; ++i) {
            uint256[11] memory r = _row(json, i);
            _configure(r);
            _check(router.previewSplit(r[0], r[1]), r, i);
        }
    }

    /// @dev End to end on every row: distribute() moves exactly the vector amounts.
    function test_parity_distribute() public {
        string memory json = _json();
        uint256 n = _count(json);
        uint64 period;
        for (uint256 i; i < n; ++i) {
            uint256[11] memory r = _row(json, i);
            _configure(r);

            uint256 expBefore = usdc.balanceOf(expenseRecipient);
            uint256 vaultBefore = usdc.balanceOf(vault);
            uint256 carryBefore = feeRouter.totalCarryReceived();
            uint256 sBefore = book.creditedSenior();
            uint256 jBefore = book.creditedJunior();
            if (r[0] > 0) _settle(router, r[0]);
            vm.prank(keeper);
            _check(router.distribute(++period, r[1]), r, i);

            assertEq(usdc.balanceOf(expenseRecipient) - expBefore, r[7], "expenses moved");
            assertEq(feeRouter.totalCarryReceived() - carryBefore, r[8], "carry moved");
            assertEq(usdc.balanceOf(vault) - vaultBefore, r[9] + r[10], "vault moved");
            assertEq(book.creditedSenior() - sBefore, r[9], "senior credited");
            assertEq(book.creditedJunior() - jBefore, r[10], "junior credited");
        }
    }

    function _configure(uint256[11] memory r) internal {
        vm.startPrank(admin);
        config.setParam("expenseCapBps", r[2]);
        config.setParam("carryBps", r[3]);
        vm.stopPrank();
        book.setHurdle(uint16(r[4]));
        _setSupply(senior, r[5]);
        _setSupply(junior, r[6]);
    }

    function _setSupply(MockERC20 t, uint256 target) internal {
        uint256 cur = t.totalSupply();
        if (cur < target) t.mint(address(t), target - cur);
        else if (cur > target) t.burn(address(t), cur - target);
    }
}
