// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";
import {Waterfall} from "../../src/libraries/Waterfall.sol";

/// @notice Parity with the NORMATIVE TypeScript waterfall (packages/shared/src/waterfall.ts).
///         Vectors: test/vectors/waterfall.json generated by scripts/gen-vectors.ts. Row formats:
///   window: [ifTarget, mmInventory, seniorCapBps, seniorCommitted, juniorCommitted, sponsorJuniorCommitted,
///            ok(0|1), reason(0 ok|1 NO_JUNIOR|2 SPONSOR_SKIN|3 IF_UNFUNDED), seniorAllocated, juniorAllocated,
///            sponsorJuniorAllocated]
///   split:  [gross, expensesRequested, expenseCapBps, carryBps, seniorHurdleBps, seniorSupply, juniorSupply,
///            expenses, carry, senior, junior]
///   mark:   [S, J, seniorImpairment, perfIndex, highWater, nav, juniorSupply, backstopAvailable,
///            S', J', seniorImpairment', perfIndex', highWater', backstopCovered, |drawdownBps|,
///            backstopDebt, backstopRepaid, backstopDebt']
///   wallet: [commit, isSponsor(0|1), totalCommitted, sponsorCommitted, totalAllocated, shares, refund]
contract WaterfallParityTest is Test {
    string internal json;
    uint256 internal count;

    function setUp() public {
        json = vm.readFile("test/vectors/waterfall.json");
        count = vm.parseJsonUint(json, ".count");
    }

    function _row(string memory section, uint256 i) internal view returns (uint256[] memory) {
        return vm.parseJsonUintArray(json, string.concat(".", section, "[", vm.toString(i), "]"));
    }

    function test_vectorCount() public view {
        assertEq(count, 256, "vector count");
    }

    function test_parity_window() public view {
        for (uint256 i = 0; i < count; i++) {
            uint256[] memory v = _row("window", i);
            assertEq(v.length, 11, "window row width");
            Waterfall.WindowResult memory r = Waterfall.allocateWindow(
                Waterfall.WindowInput({
                    ifTargetUsd: v[0],
                    mmInventoryUsd: v[1],
                    seniorCapBps: v[2],
                    seniorCommitted: v[3],
                    juniorCommitted: v[4],
                    sponsorJuniorCommitted: v[5]
                })
            );
            string memory tag = string.concat("window[", vm.toString(i), "]");
            assertEq(r.ok ? 1 : 0, v[6], string.concat(tag, " ok"));
            assertEq(uint256(r.reason), v[7], string.concat(tag, " reason"));
            assertEq(r.seniorAllocated, v[8], string.concat(tag, " seniorAllocated"));
            assertEq(r.juniorAllocated, v[9], string.concat(tag, " juniorAllocated"));
            assertEq(r.sponsorJuniorAllocated, v[10], string.concat(tag, " sponsorJuniorAllocated"));
            // sponsor priority: whenever the window succeeds the sponsor holds >= 10% of allocated Junior
            if (r.ok) {
                assertGe(
                    r.sponsorJuniorAllocated * Waterfall.BPS,
                    r.juniorAllocated * Waterfall.SPONSOR_MIN_JUNIOR_BPS,
                    string.concat(tag, " sponsor skin")
                );
            }
        }
    }

    function test_parity_split() public view {
        for (uint256 i = 0; i < count; i++) {
            uint256[] memory v = _row("split", i);
            assertEq(v.length, 11, "split row width");
            Waterfall.SplitResult memory o = Waterfall.splitDistribution(
                Waterfall.SplitInput({
                    gross: v[0],
                    expensesRequested: v[1],
                    expenseCapBps: v[2],
                    carryBps: v[3],
                    seniorHurdleBps: v[4],
                    seniorSupply: v[5],
                    juniorSupply: v[6]
                })
            );
            string memory tag = string.concat("split[", vm.toString(i), "]");
            assertEq(o.gross, v[0], string.concat(tag, " gross"));
            assertEq(o.expenses, v[7], string.concat(tag, " expenses"));
            assertEq(o.carry, v[8], string.concat(tag, " carry"));
            assertEq(o.senior, v[9], string.concat(tag, " senior"));
            assertEq(o.junior, v[10], string.concat(tag, " junior"));
        }
    }

    function test_parity_mark() public view {
        for (uint256 i = 0; i < count; i++) {
            uint256[] memory v = _row("mark", i);
            assertEq(v.length, 18, "mark row width");
            Waterfall.MarkResult memory r = Waterfall.applyMarkPnl(
                Waterfall.MarkState({
                    seniorNav: v[0],
                    juniorNav: v[1],
                    seniorImpairment: v[2],
                    perfIndex: v[3],
                    highWater: v[4],
                    backstopDebt: v[15]
                }),
                Waterfall.MarkInputs({nav: v[5], juniorSupply: v[6], backstopAvailable: v[7]})
            );
            string memory tag = string.concat("mark[", vm.toString(i), "]");
            assertEq(r.seniorNav, v[8], string.concat(tag, " S'"));
            assertEq(r.juniorNav, v[9], string.concat(tag, " J'"));
            assertEq(r.seniorImpairment, v[10], string.concat(tag, " impairment'"));
            assertEq(r.perfIndex, v[11], string.concat(tag, " perfIndex'"));
            assertEq(r.highWater, v[12], string.concat(tag, " highWater'"));
            assertEq(r.backstopCovered, v[13], string.concat(tag, " backstopCovered"));
            assertLe(r.drawdownBps, int256(0), string.concat(tag, " drawdown sign"));
            assertEq(uint256(-r.drawdownBps), v[14], string.concat(tag, " |drawdownBps|"));
            assertEq(r.backstopRepaid, v[16], string.concat(tag, " backstopRepaid"));
            assertEq(r.backstopDebt, v[17], string.concat(tag, " backstopDebt'"));
            // conservation: S' + J' == nav + backstopCovered - backstopRepaid
            assertEq(
                r.seniorNav + r.juniorNav,
                v[5] + r.backstopCovered - r.backstopRepaid,
                string.concat(tag, " conservation")
            );
            assertEq(r.pnl, int256(v[5]) - int256(v[0] + v[1]), string.concat(tag, " pnl"));
        }
    }

    function test_parity_wallet() public view {
        for (uint256 i = 0; i < count; i++) {
            uint256[] memory v = _row("wallet", i);
            assertEq(v.length, 7, "wallet row width");
            (uint256 shares, uint256 refund) = Waterfall.juniorWindowAllocation(v[0], v[1] == 1, v[2], v[3], v[4]);
            string memory tag = string.concat("wallet[", vm.toString(i), "]");
            assertEq(shares, v[5], string.concat(tag, " shares"));
            assertEq(refund, v[6], string.concat(tag, " refund"));
            assertLe(shares + refund, v[0], string.concat(tag, " never over-pays"));
        }
    }
}
