// generated by scripts/gen-abi.ts from contracts/out/IAttestedOracle.sol/IAttestedOracle.json — do not edit
export const attestedOracleAbi = [
  {
    "type": "function",
    "name": "PRICE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashPrice",
    "inputs": [
      {
        "name": "u",
        "type": "tuple",
        "internalType": "struct IAttestedOracle.PriceUpdate",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "publishedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "held",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "sourceCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "sourcesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isStale",
    "inputs": [
      {
        "name": "underlying",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latest",
    "inputs": [
      {
        "name": "underlying",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IAttestedOracle.PriceData",
        "components": [
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "publishedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "held",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "sourceCount",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minSources",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "priceOf",
    "inputs": [
      {
        "name": "underlying",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "priceWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "held",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "push",
    "inputs": [
      {
        "name": "u",
        "type": "tuple",
        "internalType": "struct IAttestedOracle.PriceUpdate",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "publishedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "held",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "sourceCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "sourcesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pushMany",
    "inputs": [
      {
        "name": "us",
        "type": "tuple[]",
        "internalType": "struct IAttestedOracle.PriceUpdate[]",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "priceWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "publishedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "held",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "sourceCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "sourcesHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "sigs",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "active",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "attestation",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "PricePushed",
    "inputs": [
      {
        "name": "underlying",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "priceWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "publishedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "held",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "sourceCount",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "signer",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SignerSet",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "active",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "attestation",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadSigner",
    "inputs": [
      {
        "name": "recovered",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotNewer",
    "inputs": [
      {
        "name": "stored",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "incoming",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "StalePrice",
    "inputs": [
      {
        "name": "underlying",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "publishedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  }
] as const;
