// generated by scripts/gen-abi.ts from contracts/out/IBookFactory.sol/IBookFactory.json — do not edit
export const bookFactoryAbi = [
  {
    "type": "function",
    "name": "bookIdOf",
    "inputs": [
      {
        "name": "book",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bookIds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bookOf",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "componentsOf",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BRTypes.BookComponents",
        "components": [
          {
            "name": "book",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "senior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "junior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mandate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "desk",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "create",
    "inputs": [
      {
        "name": "charterId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "charter",
        "type": "tuple",
        "internalType": "struct BRTypes.Charter",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "venue",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "oracle",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "sessions",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ifTargetUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mmInventoryUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mandate",
            "type": "tuple",
            "internalType": "struct BRTypes.Mandate",
            "components": [
              {
                "name": "maxInventoryUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "maxSkewBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "minQuoteWidthBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxHedgeLeverage",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMinBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMaxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "noNewRiskOffHours",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "killAtDrawdownBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "hedgeAllowRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "seniorHurdleBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "seniorCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "subscriptionWindow",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "juniorNoticeSeconds",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sponsor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "perWalletCapUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "symbol",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "takerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BRTypes.BookComponents",
        "components": [
          {
            "name": "book",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "senior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "junior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mandate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "desk",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isBook",
    "inputs": [
      {
        "name": "book",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isComponent",
    "inputs": [
      {
        "name": "a",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "BookCreated",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "book",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "components",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct BRTypes.BookComponents",
        "components": [
          {
            "name": "book",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "senior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "junior",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mandate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "desk",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ImplementationSet",
    "inputs": [
      {
        "name": "kind",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "impl",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;
