// generated by scripts/gen-abi.ts from contracts/out/MarketCharter.sol/MarketCharter.json — do not edit
export const marketCharterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "config_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "SPONSOR_BOND_DOMAIN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bondLockId",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "bondOutstanding",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeCancelled",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBookrunnerConfig"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "count",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decide",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "ok",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "juryCid",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "decisionDeadline",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escrowOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct MarketCharter.Escrow",
        "components": [
          {
            "name": "feeToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "staking",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bondOutstanding",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "expire",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "file",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct BRTypes.Charter",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "venue",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "oracle",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "sessions",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ifTargetUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mmInventoryUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mandate",
            "type": "tuple",
            "internalType": "struct BRTypes.Mandate",
            "components": [
              {
                "name": "maxInventoryUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "maxSkewBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "minQuoteWidthBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxHedgeLeverage",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMinBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMaxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "noNewRiskOffHours",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "killAtDrawdownBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "hedgeAllowRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "seniorHurdleBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "seniorCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "subscriptionWindow",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "juniorNoticeSeconds",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sponsor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "perWalletCapUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "symbol",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "takerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "get",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IMarketCharter.CharterRecord",
        "components": [
          {
            "name": "charter",
            "type": "tuple",
            "internalType": "struct BRTypes.Charter",
            "components": [
              {
                "name": "underlying",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "venue",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "oracle",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "sessions",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "ifTargetUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "mmInventoryUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "mandate",
                "type": "tuple",
                "internalType": "struct BRTypes.Mandate",
                "components": [
                  {
                    "name": "maxInventoryUsd",
                    "type": "uint128",
                    "internalType": "uint128"
                  },
                  {
                    "name": "maxSkewBps",
                    "type": "int16",
                    "internalType": "int16"
                  },
                  {
                    "name": "minQuoteWidthBps",
                    "type": "uint16",
                    "internalType": "uint16"
                  },
                  {
                    "name": "maxHedgeLeverage",
                    "type": "uint16",
                    "internalType": "uint16"
                  },
                  {
                    "name": "hedgeRatioMinBps",
                    "type": "uint16",
                    "internalType": "uint16"
                  },
                  {
                    "name": "hedgeRatioMaxBps",
                    "type": "uint16",
                    "internalType": "uint16"
                  },
                  {
                    "name": "noNewRiskOffHours",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "killAtDrawdownBps",
                    "type": "int16",
                    "internalType": "int16"
                  },
                  {
                    "name": "hedgeAllowRoot",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  }
                ]
              },
              {
                "name": "seniorHurdleBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "seniorCapBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "subscriptionWindow",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "juniorNoticeSeconds",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sponsor",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "perWalletCapUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "symbol",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "takerFeeBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "makerFeeBps",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum BRTypes.CharterStatus"
          },
          {
            "name": "filedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "decidedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "juryCid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "feePaidUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bondBkrn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "book",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isOpen",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onRetired",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "retire",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "slashSponsor",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "validate",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct BRTypes.Charter",
        "components": [
          {
            "name": "underlying",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "venue",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "oracle",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "sessions",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ifTargetUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mmInventoryUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "mandate",
            "type": "tuple",
            "internalType": "struct BRTypes.Mandate",
            "components": [
              {
                "name": "maxInventoryUsd",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "maxSkewBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "minQuoteWidthBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxHedgeLeverage",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMinBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hedgeRatioMaxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "noNewRiskOffHours",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "killAtDrawdownBps",
                "type": "int16",
                "internalType": "int16"
              },
              {
                "name": "hedgeAllowRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "seniorHurdleBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "seniorCapBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "subscriptionWindow",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "juniorNoticeSeconds",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sponsor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "perWalletCapUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "symbol",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "takerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "makerFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CharterDecided",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "approved",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "juryCid",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "book",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CharterExpired",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CharterFiled",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sponsor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "underlying",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "venue",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "symbol",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "feeUsd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "bondBkrn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CharterRetired",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeForwarded",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeRefunded",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sponsor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RetireRequested",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SponsorBondReleased",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sponsor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SponsorSlashed",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sponsor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BookNotCancelled",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BookNotCreated",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DecisionWindowClosed",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DecisionWindowOpen",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidCharter",
    "inputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "MissingJuryCid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NewBooksPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBook",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCommittee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSponsor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSponsorOrCommittee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToSlash",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SponsorNotAbandoned",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongStatus",
    "inputs": [
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum BRTypes.CharterStatus"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
