// generated by scripts/gen-abi.ts from contracts/out/MarkRegistry.sol/MarkRegistry.json — do not edit
export const markRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "config_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DOMAIN_SEPARATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MARK_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "commit",
    "inputs": [
      {
        "name": "m",
        "type": "tuple",
        "internalType": "struct BRTypes.MarkInput",
        "components": [
          {
            "name": "bookId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "navUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deployedValueUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "flowNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "inventoryRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "pnlJsonHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "receiptsRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "sig",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBookrunnerConfig"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      {
        "name": "fields",
        "type": "bytes1",
        "internalType": "bytes1"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "chainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMark",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BRTypes.Mark",
        "components": [
          {
            "name": "input",
            "type": "tuple",
            "internalType": "struct BRTypes.MarkInput",
            "components": [
              {
                "name": "bookId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "periodEnd",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "navUsd",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "deployedValueUsd",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "flowNonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "inventoryRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "pnlJsonHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "receiptsRoot",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "signer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "committedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "applied",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashMark",
    "inputs": [
      {
        "name": "m",
        "type": "tuple",
        "internalType": "struct BRTypes.MarkInput",
        "components": [
          {
            "name": "bookId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "periodEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "navUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deployedValueUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "flowNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "inventoryRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "pnlJsonHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "receiptsRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastPeriodEnd",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "periodEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestMarkId",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestMarkReplaceable",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markApplied",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "markCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "EIP712DomainChanged",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarkApplied",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarkCommitted",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "periodEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "navUsd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deployedValueUsd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "inventoryRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "pnlJsonHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "receiptsRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "signer",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarkSuperseded",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "oldMarkId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "newMarkId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "periodEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyApplied",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidShortString",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarkTooOld",
    "inputs": [
      {
        "name": "periodEnd",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nowTs",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxMarkAge",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotBook",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotConfigured",
    "inputs": [
      {
        "name": "what",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotMarkSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PeriodInFuture",
    "inputs": [
      {
        "name": "periodEnd",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nowTs",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PeriodNotAfterLast",
    "inputs": [
      {
        "name": "periodEnd",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "lastPeriodEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "PeriodNotAligned",
    "inputs": [
      {
        "name": "periodEnd",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "markInterval",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "str",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownBook",
    "inputs": [
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownMark",
    "inputs": [
      {
        "name": "markId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
