// generated by scripts/gen-abi.ts from contracts/out/IMMMandate.sol/IMMMandate.json — do not edit
export const mMMandateAbi = [
  {
    "type": "function",
    "name": "activeKeys",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "book",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "checkHedge",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct IMMMandate.HedgeParams",
        "components": [
          {
            "name": "asset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "venue",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "buy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "qtyRaw",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "notionalUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverage",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      },
      {
        "name": "allowProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "checkInventoryMove",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "toVenue",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "account",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "amountUsd",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "checkQuote",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "spreadBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "skewBps",
        "type": "int16",
        "internalType": "int16"
      },
      {
        "name": "maxNetExposureUsd",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deskHedgeNotionalUsd",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getKey",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IMMMandate.DeskKey",
        "components": [
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "inventoryTierUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMandate",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BRTypes.Mandate",
        "components": [
          {
            "name": "maxInventoryUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxSkewBps",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "minQuoteWidthBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxHedgeLeverage",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hedgeRatioMinBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hedgeRatioMaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "noNewRiskOffHours",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "killAtDrawdownBps",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "hedgeAllowRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hedgeRatioBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "config",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bookId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "book",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isActiveKey",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "kill",
    "inputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "killReason",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "killed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "offHours",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerKey",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "validUntil",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "inventoryTierUsd",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "remandate",
    "inputs": [
      {
        "name": "m",
        "type": "tuple",
        "internalType": "struct BRTypes.Mandate",
        "components": [
          {
            "name": "maxInventoryUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxSkewBps",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "minQuoteWidthBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxHedgeLeverage",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hedgeRatioMinBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "hedgeRatioMaxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "noNewRiskOffHours",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "killAtDrawdownBps",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "hedgeAllowRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeKey",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "KeyRegistered",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "validUntil",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "inventoryTierUsd",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "KeyRevoked",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Kill",
    "inputs": [
      {
        "name": "reason",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Remandated",
    "inputs": [
      {
        "name": "mandateHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FloatCapExceeded",
    "inputs": [
      {
        "name": "attemptedRaw",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "capRaw",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HedgeLeverageTooHigh",
    "inputs": [
      {
        "name": "leverage",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "max",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "HedgeNotAllowed",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "venue",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "HedgeRatioOutOfBand",
    "inputs": [
      {
        "name": "ratioBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InventoryLimit",
    "inputs": [
      {
        "name": "attemptedUsd",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxUsd",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "KeyExpired",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "MandateKilled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotDeskKey",
    "inputs": [
      {
        "name": "key",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OffHoursNewRisk",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuoteWidthTooNarrow",
    "inputs": [
      {
        "name": "widthBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "minBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "SkewTooWide",
    "inputs": [
      {
        "name": "skewBps",
        "type": "int16",
        "internalType": "int16"
      },
      {
        "name": "maxBps",
        "type": "int16",
        "internalType": "int16"
      }
    ]
  },
  {
    "type": "error",
    "name": "SpotShortNotAllowed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TierBondMissing",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "locked",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
