// generated by scripts/gen-abi.ts from contracts/out/IOrderlyVault.sol/IOrderlyVault.json — do not edit
export const mockOrderlyVaultAbi = [
  {
    "type": "function",
    "name": "delegateSigner",
    "inputs": [
      {
        "name": "data",
        "type": "tuple",
        "internalType": "struct IOrderlyVault.VaultDelegate",
        "components": [
          {
            "name": "brokerHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "delegateSigner",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "data",
        "type": "tuple",
        "internalType": "struct IOrderlyVault.VaultDepositFE",
        "components": [
          {
            "name": "accountId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "brokerHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenAmount",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "depositTo",
    "inputs": [
      {
        "name": "receiver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "tuple",
        "internalType": "struct IOrderlyVault.VaultDepositFE",
        "components": [
          {
            "name": "accountId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "brokerHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenAmount",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "getAllowedToken",
    "inputs": [
      {
        "name": "tokenHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDepositFee",
    "inputs": [
      {
        "name": "receiver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "tuple",
        "internalType": "struct IOrderlyVault.VaultDepositFE",
        "components": [
          {
            "name": "accountId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "brokerHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenAmount",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;
