// Generates packages/shared/src/abi/*.ts (viem-typed `as const` ABIs) from contracts/out.
// Prefers the implementation artifact; falls back to the interface while an implementation is missing.
//   bun scripts/gen-abi.ts            (run `bun run contracts:build` first)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const OUT = resolve(ROOT, "contracts/out");
const DEST = resolve(ROOT, "packages/shared/src/abi");

// logical name -> candidate artifacts (first found wins)
const CONTRACTS: Record<string, string[]> = {
  BookrunnerConfig: ["BookrunnerConfig", "IBookrunnerConfig"],
  BkrnToken: ["BkrnToken", "ERC20"],
  BkrnStaking: ["BkrnStaking", "IBkrnStaking"],
  BkrnFeeRouter: ["BkrnFeeRouter", "IBkrnFeeRouter"],
  Backstop: ["Backstop", "IBackstop"],
  MarkRegistry: ["MarkRegistry", "IMarkRegistry"],
  RevenueRouter: ["RevenueRouter", "IRevenueRouter"],
  Book: ["Book", "IBook"],
  Tranche: ["Tranche", "SeniorTranche", "ITranche"],
  UnderwritingVault: ["UnderwritingVault", "IUnderwritingVault"],
  MarketCharter: ["MarketCharter", "IMarketCharter"],
  RiskCommittee: ["RiskCommittee", "IRiskCommittee"],
  BookFactory: ["BookFactory", "IBookFactory"],
  MMMandate: ["MMMandate", "IMMMandate"],
  BookrunnerDesk: ["BookrunnerDesk", "IBookrunnerDesk"],
  HedgeExecutor: ["HedgeExecutor", "IHedgeExecutor"],
  StockTokenRegistry: ["StockTokenRegistry", "IStockTokenRegistry"],
  AttestedOracle: ["AttestedOracle", "IAttestedOracle"],
  PoolEngine: ["PoolEngine", "IPoolEngine"],
  PoolEngineAdapter: ["PoolEngineAdapter", "IPoolEngineAdapter"],
  OrderlyAdapter: ["OrderlyAdapter", "IOrderlyAdapter"],
  MockERC20: ["MockERC20"],
  MockOrderlyVault: ["MockOrderlyVault", "IOrderlyVault"],
  MockSwapRouter: ["MockSwapRouter", "ISwapRouter02"],
};

function findArtifact(name: string): { abi: unknown[]; from: string } | null {
  // forge layout: out/<File>.sol/<Contract>.json — search all .sol dirs for <Contract>.json
  const glob = new Bun.Glob(`*.sol/${name}.json`);
  for (const rel of glob.scanSync({ cwd: OUT })) {
    const json = JSON.parse(readFileSync(resolve(OUT, rel), "utf8"));
    if (Array.isArray(json.abi)) return { abi: json.abi, from: rel.replaceAll("\\", "/") };
  }
  return null;
}

if (!existsSync(OUT)) {
  console.error("contracts/out missing — run `bun run contracts:build` first");
  process.exit(1);
}
mkdirSync(DEST, { recursive: true });

const index: string[] = ["// generated by scripts/gen-abi.ts — do not edit"];
const report: string[] = [];
for (const [logical, candidates] of Object.entries(CONTRACTS)) {
  let found: { abi: unknown[]; from: string } | null = null;
  for (const c of candidates) {
    found = findArtifact(c);
    if (found) break;
  }
  if (!found) {
    report.push(`  MISSING ${logical}`);
    continue;
  }
  const varName = `${logical[0]!.toLowerCase()}${logical.slice(1)}Abi`;
  const body = `// generated by scripts/gen-abi.ts from contracts/out/${found.from} — do not edit\nexport const ${varName} = ${JSON.stringify(found.abi, null, 2)} as const;\n`;
  writeFileSync(resolve(DEST, `${logical}.ts`), body);
  index.push(`export { ${varName} } from "./${logical}";`);
  report.push(`  ${logical.padEnd(20)} <- ${found.from}`);
}
writeFileSync(resolve(DEST, "index.ts"), `${index.join("\n")}\n`);
console.log(`ABIs written to packages/shared/src/abi:\n${report.join("\n")}`);
